### ISSUE TITLE
Consider separating DelimitedText/FixedWidthRecordReader

### ISSUE THREAD

**Issue by atifaziz** [slorion/nlight#1]
Back in 2012, I published your [fast & excellent CSV reader](http://www.codeproject.com/KB/database/CsvReader.aspx) as the [NuGet package `LumenWorks.Framework.IO`](https://www.nuget.org/packages/LumenWorks.Framework.IO/) so that I (and as a natural extension, others) could use it conveniently via NuGet. Then I stumbled across [your comment](https://github.com/phatcher/CsvReader/issues/8#issue-114655310) on phatcher/CsvReader#8:

> Hello, I am the original author of FastCsvReader. It's been a long while since I wrote that library and I had a replacement which was on Codeplex that I recently put on github. Upon seeing your project, I thought it might interest you.
> 
> You can take a look at https://github.com/slorion/nlight for the library. The CSV reader is https://github.com/slorion/nlight/blob/master/src/NLight/IO/Text/DelimitedRecordReader.cs. You can go to https://github.com/slorion/nlight/tree/master/src/NLight.Tests.Unit/IO/Text to see it in action or https://github.com/slorion/nlight/tree/master/src/NLight.Tests.Benchmarks to benchmark it (including against my old reader).

Have you considered maintaining & releasing `DelimitedTextRecordReader` and `FixedWidthRecordReader` as a separate library, package & repo? It would make it easier to use & make contributions. As it stands, dragging in the whole of NLight with it seems a bit of an overkill.

**Comment by slorion** [comment]
I considered it, but those two classes depend on many others in NLight. What would make more sense would be to split NLight on a namespace basis, but given the size of the library, I don't see the point of doing that for the time being. NLight should be considered a helper library rather than a library aimed at a specific need such as JSON.NET or the like.

**Comment by atifaziz** [comment]
> but those two classes depend on many others in NLight.

Perhaps that's a sign that it's doing too much and that it could be made more modular. For example, should a CSV parser be concerned with type conversions & typed data? I reckon those bits can always be layered on top.

> but given the size of the library

If it was only about the size.

> I don't see the point of doing that for the time being

I would have imagined that putting the source out here would be for the purpose of engaging with the community, to contribute & collaborate.

> NLight should be considered a helper library rather than a library aimed at a specific need such as JSON.NET or the like.

Thanks for clearing the scope but I still don't see why separating out some bits make NLibrary any less of a helper. In fact, it can take the dependency and bundle together various namespaces.

If your goal is to keep NLibrary as a single distribution unit then there's also another alternative to consider that won't require so much slicing and dicing. Why not setup a separate VS project in the same solution that _links_ the necessary files together into another redistributable assembly? That way, you can continue to ship NLight as well as a stand-alone CSV parsing library yet still manage the two through this repo & a single set of shared sources. Just a thought. In the end, it's your choice of course and I'm not going to pester you on about it. :smile:

BTW, this was not a question, but a request for enhancement. I'll admit that I did end my opening comment with more or less a question.

**Comment by slorion** [comment]
The dependencies I was referring to are NLight.Core (for helpers) and NLight.Text (for parsing escaped sequences, etc.). If you feel some parts could be refactored, feel free to make a pull request.

I prefer to keep NLight distributed as a single library and would certainly not want to go the linked files route (which I also considered). I personally like to keep things simple and easily maintainable (including for myself), and that is in line with that goal.

**Comment by atifaziz** [comment]
> The dependencies I was referring to are NLight.Core (for helpers) and NLight.Text (for parsing escaped sequences, etc.).

That's how I read it.

>  If you feel some parts could be refactored, feel free to make a pull request.

I'm not sure at this stage if I want to spend the energy to refactor and do a PR only to find out in the end that it may not belong with the goal, scope & direction you have with NLight. I understand NLight is your library and you have opinions about how wish to keep it. `LumenWorks.Framework.IO` has served me (and I believe many others) tremendously well over the years and I have personally not come across a single bug so I don't have a burning itch to scratch (solve a problem that may not be there). The only issue that's been there over the years is any collective effort to maintain & improve the library so that it could become the go-to CSV parser for .NET (it's always too easy to create yet another abandoned fork). I thought this repo might have been that forum or catalyst but looks not. In any event, keep up the great work & thanks again!

**Comment by slorion** [comment]
That's flattering to imply that my parser could maybe be the go to reference for CSV parsing. I certainly do not have that pretense and the popularity of my previous library took me by surprise to tell the truth. My main goal with this library is simply to share code that I know is well tested (used in production) and answers to a certain standard of quality. Because I fail to see the need to split the library, besides to improve clarity of purpose, maybe you can tell me what is your concern about using a specific part of a general purpose library ? Is it technical or purely semantic ?

Another thing I could do is target other versions of .NET, but I chose not to because I lack the time and motivation to maintain many versions and I am somewhat opinionated about not encouraging inertia.

**Comment by atifaziz** [comment]
> That's flattering to imply that my parser could maybe be the go to reference for CSV parsing. I certainly do not have that pretense…

We all stand on each other's shoulders. Point was, if the community pulls together with some stewardship then it stands a good chance to become the go-to library for the community and by the community (with people contributing fixes & ideas for further development). The onus is then on the community to do a great job and in a selfless way.

> my previous library took me by surprise to tell the truth.

It shouldn't be surprising if you fill a gap and take the trouble to fill it well. Question is always then, “What next?”

> My main goal with this library is simply to share code that I know is well tested (used in production) and answers to a certain standard of quality.

No doubt but we're just talking about how you slice & dice that library. Doesn't sound painful or a management nightmare from a tooling (VS), hosting (GitHub) and distribution (NuGet) perspective.

> maybe you can tell me what is your concern about using a specific part of a general purpose library ? Is it technical or purely semantic ?

It can't be technical because [I understand that with JIT we pay for only what we use](https://github.com/elmah/Elmah/issues/25#issuecomment-134586018) and we don't incur any dependency if a code path is never used. That said, the truth is that we've moved beyond that simple model. For example, your [NLight depends on Rx](https://github.com/slorion/nlight/blob/3848da321e2ff0c2347e7c5955ddda4284a474db/src/NLight/paket.references#L1) but [doesn't declare that dependency in its own package](https://github.com/slorion/nlight/blob/3848da321e2ff0c2347e7c5955ddda4284a474db/src/NLight/NLight.nuspec). But say it did. Now when one pulls NLight for just CSV parsing, one also pulls the entire weight of Rx, which is never needed or used at run-time. When distributing the binaries, some may care about the extra baggage.

On the semantic side, I guess it's more a question of what it means to do open source successfully but that can be a big discussion & I'm not here to teach you because Lord knows I've [failed](https://elmah.github.io/) [miserably](https://github.com/atifaziz/Jayrock) at it. :smile: 

> Another thing I could do is target other versions of .NET but I chose not to because I lack the time and motivation to maintain many versions

Aye, I've been there so I understand you completely but doesn't mean someone else may not be willing to pitch in there as an incremental improvement.

> and I am somewhat opinionated about not encouraging inertia.

That nails it then I guess but still appreciate you being up-front about it.

**Comment by slorion** [comment]
I think what we are really talking about is how to market the library and having a singular purpose certainly helps, that we can agree on. On the other hand, I disagree that it is a simple matter of slide&dice. I think it would be very bad design to have exactly the same code in two distinct libraries, namely the parts in Core, Text.Parsing and eventually others. It would be confusing from a user perspective and would lead to namespace clashes if some user happens to use both libraries at the same time.

Also, we are now talking about text readers, but what about the TransactionManager which I think could also be a candidate to be in a library of its own ? Or the tree traversals in Collections .. one could improve on that and make a full fledged tree/graph library, something which is sorely lacking in .NET (beside QuickGraph). As things stand, there is not enough meat to justify making all of these a library on its own. And if it ever happens to be the case, then I would be much more inclined to split the library on a namespace basis, say NLight.Collections, NLight.IO, etc.

About Rx, it should be listed as a dependency and I thought it was happening automatically. I will fix that asap. That said, I don't think depending on Rx is a heavy burden. I consider what that library offers to be a core fonctionality of any platform and indeed, ReactiveStreams (hhttp://www.reactive-streams.org/) is now standardized and is considered for inclusion in JDK9. It is something that is pervasive once you start using it as it more or less replace event based design and so, I chose to make it a hard dependency.

**Comment by slorion** [comment]
I fixed the dependency issue by using `paket pack` instead of `nuget pack`.

**Comment by atifaziz** [comment]
> I think it would be very bad design to have exactly the same code in two distinct libraries…It would be confusing from a user perspective

It would be confusing if you don't describe it anywhere. It's confusing right now anyhow for anyone looking for an authoritative package that's just an evolution of your original parser (and they go looking for a parser, not a helper library).

> and would lead to namespace clashes if some user happens to use both libraries at the same time.

No one would do this in their right mind if they are writing or in control of the app/host. The only clash that can happen is indirectly via libraries & that too if the assemblies are weak-named. However, people shipping libraries usually cover their behinds by often internalizing external dependencies via ILMerge or source inclusion.

As for splitting up NLight, where you draw the lines and how far you go depends no what you're after as an end-goal & how much time you have to spare to get there. I personally have lots of tiny projects and packages that often do one thing, try do it well and then others that build on them. For example, [MoreLINQ](https://morelinq.github.io/) is shipped as a [complete library](https://www.nuget.org/packages/morelinq/), [PCL](https://www.nuget.org/packages/MoreLinq.Portable/) as well [C# source packages](https://www.nuget.org/packages?q=morelinq+c%23+sources) for direct & internal inclusion into projects. In the last case, you can pick operator by operator because most of them are independent of each other or even bring them all in via a [bundling package](https://www.nuget.org/packages/MoreLinq.Source.MoreEnumerable/). I'll admit it's not easy to manage but it was certainly an interesting exercise with some lessons learned. In [other](https://github.com/atifaziz/AngryArrays) [cases](https://github.com/atifaziz/Interlocker), I've had no second thoughts.

**Comment by slorion** [comment]
I still think I will cross that bridge when I get to the proverbial river. If one, for some reasons, absolutely needs a dedicated library, then there are already good authoritative sources with FileHelpers (http://www.filehelpers.net/) or even CsvReader (http://www.csvreader.com/). Their scope is much more focused, their library covers much more ground in their area of expertise and their level of support is much more involved. I don't want to go there, I have many other things going on in my life and this is where I draw the line on my contributions. Myself, I would use any tool that fits the project requirements best, no matter if it's in a general purpose library or a dedicated one. If it's super heavy and drag along the universe with it, sure, that will be a minus point, but I don't think my library is there yet. In your particular case, if a lack of focus prevents you from using my code, then so be it.

**Comment by atifaziz** [comment]
@slorion That's fine and understand your stance.
