### ISSUE TITLE
Incorrect DelimitedRecordWriter column ordering 

### ISSUE THREAD

**Issue by TheChemerson** [slorion/nlight#10]
The order of columns in the header is incorrect when header is written through the WriteColumnHeaders method with includeDataType set to false.  Here is a quick test:
```csharp
using (var writer = new DelimitedRecordWriter(new StreamWriter("c:\\temp\\header_test.txt", false))) {
    writer.Columns.Add(new DelimitedRecordColumn("A"));
    writer.Columns.Add(new DelimitedRecordColumn("B"));
    writer.Columns.Add(new DelimitedRecordColumn("C"));
    writer.Columns.Add(new DelimitedRecordColumn("D"));
    writer.WriteColumnHeaders(false);
}
```
The expected behaviour is the column header would appear as "A","B","C","D".  Please note that the method behaves as expected when includeDataType is set to true.

**Comment by slorion** [comment]
Thank you for the detailed bug report, I pushed an update to nuget.
