### ISSUE TITLE
NuGet compatibility with .NET v4.5.2 and above

### ISSUE THREAD

**Issue by avoll** [slorion/nlight#11]
Hi, thank you for the great libraries!

I have been using your older text reader package with CsvReader, and now wanted to try NLight out, but installing via nuget I'm getting this error:

NLight 1.1.3 is not compatible with .NETFramework,Version=v4.5.2.

Using VS Pro 2015 Update 3
.NET V4.6.01055

Please have a look when you get a chance,
Thank you,
Alex

**Comment by slorion** [comment]
NLight requires .NET 4.6.2 which is an in-place update of .NET 4.5.2
