### ISSUE TITLE
Sample use

### ISSUE THREAD

**Issue by RichardAD** [slorion/nlight#12]
Is there any sample code for using the reader to create a filled DataTable ?

Something analogous to
`using (var dataAdapter = new SqlDataAdapter(queryString, sqlConnStr))
{
    var dataTable = new DataTable();
    dataAdapter.FillSchema(dataTable, SchemaType.Mapped);
}
`

**Comment by slorion** [comment]
The CSV reader implements `IDataReader`, so you can simply call `table.Load(reader)`.

**Comment by RichardAD** [comment]
Hi Sébastien :

Thanks for the reply.  I have tried as you suggested.  The following code
does not error or throw exceptions, however the DataTable has no rows in it.

            filename = "SampleAnalysis.csv";
            DataTable csvData = new DataTable();
            DelimitedRecordReader reader = new DelimitedRecordReader(new
StreamReader(filename));
            csvData.Load(reader);

Can you make a suggestion on how to proceed or learn more about data table
load ?

Regards

Richard

On Sat, Feb 18, 2017 at 12:58 PM, Sébastien Lorion <notifications@github.com

**Comment by slorion** [comment]
It looks like the internal behavior of the `DataTable.Load` function has changed at some point. It is calling `IDataReader.FieldCount` before calling `IDataReader.GetSchemaTable` and if the field count is 0, it will not get the schema. One quick workaround is to call `reader.ReadColumnHeaders()` before calling `table.Load(reader)`.
