### ISSUE TITLE
Implementation of escaped not working?

### ISSUE THREAD

**Issue by JMoelands** [slorion/nlight#13]
First, thanks for the great library, I can not read this comma separated string, based on this usage pattern of the library;
using (TextReader reader = File.OpenText(@"D:\Example Data\Fixed Batting\Work\test.txt"))
            {
                using (NLight.IO.Text.DelimitedRecordReader txtReader = new DelimitedRecordReader(reader))
                {
                    // txtReader.DelimiterCharacter = ',';
                    //txtReader.QuoteCharacter = '\"';
                    txtReader.AdvancedEscapingEnabled = true;
                    //EscapedStringParser.EscapeCharacter

                    while (txtReader.Read() == ReadResult.Success)
                    {

                    }
                }
            }

2064,"campbmi02","","",1850,,,"Ireland","",,1926,1,12,"USA","NJ","Elizabeth","Mike","Campbell","Also known as \"Mat Campbell\"","Mathew",,,,,,"1873-04-28","","campbma01","campbma01","campm101","campbma01","campbma01"

Exception Details:
{"The CSV appears to be corrupt near record '0' field '18 at position '112'. Current raw data : '2064,\"campbmi02\",\"\",\"\",1850,,,\"Ireland\",\"\",,1926,1,12,\"USA\",\"NJ\",\"Elizabeth\",\"Mike\",\"Campbell\",\"Also known as \\\"\\\"Mat Campbell\\\"\\\"\",\"Mathew\",,,,,,\"1873-04-28\",\"\",\"campbma01\",\"campbma01\",\"campm101\",\"campbma01\",\"campbma01\"\r\n2065,\"campbmi01\",\"\",\"\",1964,2,17,\"USA\",\"WA\",\"Seattle\",,,,,,,\"Mike\",\"Campbell\",,\"Michael Thomas\",,210,75.0,\"R\",\"R\",\"1987-07-04\",\"Hawaii\",\"campbmi01\",\"campbmi01\",\"campm001\",\"campbmi01\",\"campbmi01\"'."}

**Comment by slorion** [comment]
You need to escape the ```"``` inside the field value ```"Also known as "Mat Campbell""``` which incidentally is the 18th field of the first record, with the first non-escaped quote at position 112 in the file.

**Comment by JMoelands** [comment]
The quote is escaped with a backslash?

**Comment by JMoelands** [comment]
this is the original row:
2064,"campbmi02","","",1850,,,"Ireland","",,1926,1,12,"USA","NJ","Elizabeth","Mike","Campbell","Also known as \"Mat Campbell\"","Mathew",,,,,,"1873-04-28","","campbma01","campbma01","campm101","campbma01","campbma01"

**Comment by JMoelands** [comment]
the backslash is removed from the comments when posting in this form

**Comment by JMoelands** [comment]
![example](https://user-images.githubusercontent.com/29478320/27219723-013c00c2-5283-11e7-8383-82ba9b8e40b9.png)

**Comment by slorion** [comment]
Could you attach the text file or at least the part you show ? I will have a look at it, it's hard to see if there is a syntax problem looking at an image.

**Comment by JMoelands** [comment]
[test.txt](https://github.com/slorion/nlight/files/1080285/test.txt)

**Comment by JMoelands** [comment]
here you have! thanks for taking the time to look at it!

**Comment by JMoelands** [comment]
[test1.txt](https://github.com/slorion/nlight/files/1080292/test1.txt)

This was the original one, the above is with double quotes, both not work

**Comment by JMoelands** [comment]
The library of Andrew Rissing on code project is parsing it correctly with these settings;

using (GenericParser parser = new GenericParser())
            {
                parser.ColumnDelimiter = ',';
                parser.SetDataSource(@"D:\Example Data\Fixed Batting\Work\test.txt");
                parser.FirstRowHasHeader = true;
                //parser.SkipStartingDataRows = 10;
                parser.MaxBufferSize = 4096;
                parser.MaxRows = 500;
                parser.TextQualifier = '\"';
                parser.EscapeCharacter = '\\';
                while (parser.Read())
                {

                }
            }

**Comment by JMoelands** [comment]
But I like your (datareader) implementation more!

**Comment by slorion** [comment]
Well, to my surprise, it seems like I forgot ```\"``` as a valid escape sequence when advanced escaping is enabled. Doubling the quote works as expected. I will add this case and publish a new version asap.

**Comment by JMoelands** [comment]
Great Thanks a lot!

**Comment by JMoelands** [comment]
works like a charm! thanks m8 :)
