### ISSUE TITLE
Can't read this separated string

### ISSUE THREAD

**Issue by JMoelands** [slorion/nlight#14]
Hi,

Back again :) I have a new issue, which I can not read this string (the comma's are the separator)
,"Hammer,Hammerin' Hank,Bad Henry",

This is the whole record if you want to test your-selfe:
1,"aaronha01","","aaronha01h",1934,2,5,"USA","AL","Mobile",,,,,,,"Hank","Aaron",,"Henry Louis","Hammer,Hammerin' Hank,Bad Henry",180,72.0,"R","R","1954-04-13","","aaronha01","aaronha01","aaroh101","aaronha01","aaronha01"

This is the code:

using (NLight.IO.Text.DelimitedRecordReader txtReader = new DelimitedRecordReader(reader))
                    {
                        txtReader.DelimiterCharacter = ',';
                        txtReader.QuoteCharacter = '\"';
                        txtReader.AdvancedEscapingEnabled = true;
                        txtReader.ColumnHeaderTypeSeparator = ',';
                        txtReader.ReadColumnHeaders();
                        col = txtReader.Columns;
}

**Comment by JMoelands** [comment]
Exception Details:
An exception of type 'System.TypeLoadException' occurred in mscorlib.dll but was not handled in user code

Additional information: Could not load type 'Hammerin' Hank' from assembly 'NLight, Version=1.1.5.0, Culture=neutral, PublicKeyToken=798b913a26e7bdbb'.

**Comment by slorion** [comment]
`ColumnHeaderTypeSeparator` is meant to be the separator used when column data types are specified, as in:

````first:String,last:String,birth:DateTime````

By settings ',' as `ColumnHeaderTypeSeparator` and calling `ReadColumnHeaders()`, the reader tries to interpret the first record as `<column name>,<column type>;<...>`, which it cannot really do ... Furthermore, using the same character for `DelimiterCharacter` and `ColumnHeaderTypeSeparator` cannot work as the parser cannot distinguish between a column type and another column.

**Comment by JMoelands** [comment]
No issue, indeed when not using parse header, (there is no header), the problem is solved. Parsing of this string went good! thanks
