### ISSUE TITLE
Toolkit documentation?

### ISSUE THREAD

**Issue by btg-admin** [slorion/nlight#15]
I found your project from your comment on the Fast CSV Reader from CodeProject.  I'm sort of running tests with it to try and figure out how it works, but I was wondering if there is any documentation available?  By that I mean a listing of methods, properties, etc and a brief description of each.  I don't see any examples anywhere to look at for reference on how to use your library.

This really isn't an issue against the library, I just wasn't sure where to contact you to ask this question.

Thanks,

Tom

**Comment by slorion** [comment]
Hi Tom,

There is no doc per se, but you can have a look at unit tests for examples on how to use the library. I have put in a lot of efforts to make the library intuitive, so while having documentation is always a plus, or should even be required as part of publishing a library, I think you can work around this limitation.
