### ISSUE TITLE
Not able to configure row-separator on DelimitedRecordReader

### ISSUE THREAD

**Issue by JMoelands** [slorion/nlight#17]
Hi,

Maybe not an issue, but why is the row terminator (\r\n) hard coded in your solution. For example I have a data set where the last column also contains a | -> my row separator is a |\r\n
test1|test2|test3|test4|test5|test6|

Anyway, this is just a practical example, why did you choose to implement this? And are you willing to support a array of char's defining the row terminator instead of the code;

protected virtual bool IsNewLine(char c)
{
	return (c == '\r' || c == '\n');
}

Regards!

**Comment by slorion** [comment]
Since your field separator is `|`, if your record ends with `|\r\n`, it means it contains an empty field at the end. [RFC 4180](https://tools.ietf.org/html/rfc4180) (as close as a standard we can get) states that `CRLF` is the record terminator so that is why I hardcoded it.
