### ISSUE TITLE
Excel conform seperator declaration on first line

### ISSUE THREAD

**Issue by th0masj0** [slorion/nlight#20]
Hey,

I'm start working with your lib especially with DelimitedRecordWriter and DelimitedRecordReader. My aim is to create csv files wich supports excel viewing. Because of european standards excel will use semicolon as default delimiter. Because I'm just want to use comma. Excel supports declaration of delilmiter on first line via:

`sep=,`

I have found no solution to handle this with your lib. Have you any suggestions? How can I insert this declaration at write time and ignore it later at reading?

Regards 
Thomas

**Comment by slorion** [comment]
Since both `DelimitedRecordReader` and `DelimitedRecordWriter` take a `System.IO.TextReader` as input, you are free to do preprocessing before reading/writing with nlight classes.

**Comment by th0masj0** [comment]
Thx, this works.
