### ISSUE TITLE
Quotation and null values

### ISSUE THREAD

**Issue by th0masj0** [slorion/nlight#21]
Hey,

my default scenario for writing csv (with DelimitedRecordWriter) is using no quotations as long as they are not necessary. I've established setting UseQuoteCharacter to false will disable quotation fully. Also multiline values will then not be quoted. Same happens with quotes in values which will not be escaped. Is there another method to do this without preprocessing all values?

Relating to first question I try to differ from empty (string) values and NULL values. Therefore two ways exist for me:
- quote all values instead of NULL values (which are then simply two delimiters).
- Use a special marker like NULL or #N/A or \N. This marker should also never be quoted.

What is your favorite mechanismn to distinguish between empty and null?

Regards Thomas

**Comment by slorion** [comment]
For first question, you can toggle the `UseQuoteCharacter` when writing values, usually on a per column basis. See this related discussion: #19.

For second question, I prefer to use a marker, quoted or not. This is how must database import tools deal with this issue.

**Comment by th0masj0** [comment]
For the marker problem I've written some processing of my row values. It replaces the NULL-values with marker at writing and vice versa at reading.

But the first question is not as simple as that. The default should be not using quotes. Only in case quotes are necessary they should be used. Therefore all situations must be considered which should be (in best case) part of the lib. Otherwise I'm forced to write something for switching `UseQuoteCharacter` ON and OFF in problematic cases. I think they are:
- A delimiter ist part of value
- The value contains line breaks
- The value contains quotes

Have I missed something? Is it possible to integrated this in library?

**Comment by slorion** [comment]
Looks like you cover most of the cases where quoting is necessary, but others may come up. Checking for all these is not free as it requires parsing values. May I ask why you are not simply quoting all string fields?

**Comment by th0masj0** [comment]
I do this mostly because of compatibility with other apps. Also because the absence and existence of the quotes could have a meaning. It will be a difference wether something is written as "3" or 3. Same with "NULL" or NULL (f.e. excel will determine cell/column type based on it). Therefore enabling quotes per default is not an option.

Like in the Example.txt of #19 the rows should have following form:
Age ; Firstname ; Lastname ; Address
23 ; Thomas ; Jeffry ; "Sample Street 10\r\n44321 Munich"
54 ; Michael ; NULL ; NULL

Another problem in my case is that I get a List of strings without knowing column source types at write time. Therefore I could not switch specific for type like int => UseQuoteCharacter OFF, string => UseQuoteCharacter ON.

If possible I would also for string columns don't use quotes at all, but then reading will be incorrect. f.e. writing a "problematic" string containing delimiter in it with your lib and UseQuoteCharacter = False will result in an error reading the file (with your lib). Is this a desired behaviour? Perhaps it will be a little more robust with auto quotes by necessity.

**Comment by slorion** [comment]
I do really think that always quoting string fields is the most sensible way to go, if not the best, for consistency, simplicity, reliability and performance reasons.

As for quoting other field types and null values, I agree it is better not to do so and the writer could be modified to be more intelligent. It would require that the library user configure the `Columns` property and the `DelimitedRecordWriter` would need to track which column is being written. That's the simple case and even then, what to do with e.g. floating point values written with "," as decimal separator and "," is also used as field separator? I'm sure there are many other edge cases. For all other cases, including when you don't know the data type as you mentioned, then only an application specific logic can be applied, so I am not sure adding that intelligence is worth it. From my perspective, it's a nice-to-have and my time is limited atm.

**Comment by th0masj0** [comment]
For Floating points with "," and delimiter = "," it is clear that this must be quoted. Otherwise the file will be malformed. But you are right that this handling can be tricky. Therefore I have encapsulated this in my app. Perhaps I can share this if someone has this requirement in the future too. My solution is based on a configuration value `QuoteUsage` as enumeration with values All, Strings, Problematic, None. This is far enough for me.

Thank you very much for your incredible fast and professional support. See you!
Thomas

**Comment by slorion** [comment]
My pleasure! I know first hand that dealing with input data on which we have no control can be tricky.

Feel free to share your code here (as a gist perhaps) and if I can integrate it easily, I will do so.
