### ISSUE TITLE
Cant update NLight for .NET Framework projects targetting < 4.7.1

### ISSUE THREAD

**Issue by drake2k** [slorion/nlight#22]
Hi,

Since you migrated to netstandard 2.0 we cant upgrade NLight if our projects targets a version of the framework lower than 4.7.1 because the framework does not include the required dependencies for netstandard20.

Would be great if you could add a .NET 4.0/4.5 lib in the nuget package as well as the netstandard2.0 dll

Thanks

**Comment by slorion** [comment]
Hello!

.NET 4.0 is missing some key features (e.g. in `System.Threading.Tasks`) so the option of supporting it is pretty much discarded. That leaves us with .NET 4.5 ... netstandard 2.0 is supported by .NET 4.6.1, which is already quite old and a minor upgrade from .NET 4.5 (see https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/runtime/4.5-4.6). So would it be possible to rather update your libraries to use a newer .NET version instead?

**Comment by drake2k** [comment]
Hi,

I was suggesting 4.5 just because its what most package we use provide, we actually currently target .NET4.7, and for us its difficult to upgrade even to 4.7.1 (locked down corporate environment).

The problem is that while 4.7 is able to consume netstandard20 libraries, it is missing some files required by netstandard libraries. If we had VS2017/2015 we'd have an easy solution but we are stuck on 2013 for the moment.

see
https://github.com/dotnet/standard/issues/514

I understand that this is a very specific request, and that might be simply to much work for you versus the benefits.

**Comment by slorion** [comment]
VS 2013 ?! Wow, I feel your pain :) Ok, I will take a look at the issue you linked because I was not aware of the required shenanigans. If not too much work, then sure.

**Comment by slorion** [comment]
Well, that was easy, I just needed to add another target in the csproj. `System.Threading.AsyncLocal<T>` does not exist in .NET 4.5, so .NET 4.6 is the earliest version I can support. v2.1.1 should be available on nuget soon.
