### ISSUE TITLE
MalformedRecordException when field contains multiple quoted strings

### ISSUE THREAD

**Issue by cantcompile** [slorion/nlight#23]
In the example below the second field will throw MalformedRecordException when parsed.  The field separator is a comma. 

field1, "string1";"string2", field3

While the format is unusual, the file comes from a 3rd party application, I have not found anything that says it is invalid.  Excel 2010 will import it as one field, although it does remove some of the double quotes but not all.

**Comment by donvnielsen** [comment]
There's a semi colon between "string 1" and "string 2"

**Comment by cantcompile** [comment]
That is correct, the semi-colon is part of the field and is not a delimiter.  Everything between the two commas should be treated as one field.

**Comment by slorion** [comment]
Per RFC 4180 (https://tools.ietf.org/html/rfc4180), nested quotes need to be escaped by doubling them. This reader also allow quotes to be escaped with a backslash (e.g. `"string1\";\"string2"`). While Excel can be quite sure that an user will validate the import result, this reader cannot and so, using arbitrary heuristics is not an option.

**Comment by cantcompile** [comment]
The quotes are not supposed to be nested.  I had read that RFC and this format probably does not follow the spec.  I have reported it to the vendor.  Here is a sample of the actual data I received.  

,"=HYPERLINK("https://eicc2.augusoft.net/index.cfm?method=ClassInfo.ClassInformation&int_class_id=331&int_category_id=1&int_sub_category_id=48&fromRpt=1";"Learn More/Register")",

Thank you for looking at this and making your library available.

**Comment by slorion** [comment]
If the vendor is unwilling to fix their output format, your best bet would be a preprocessing step to fix those cases and/or use the `ParseErrorAction` property and `ParseError` event of the reader.

**Comment by atifaziz** [comment]
Technically, per [RFC 4810](https://tools.ietf.org/html/rfc4180):

> Spaces are considered part of a field and should not be ignored

Therefore that second field should be read as one: <kbd>SPACE</kbd>`"string1";"string2"`. It starts with a space so it should be assumed to be unquoted and any double-quotes appearing within can be parsed un-escaped/verbatim. The spec does however go on to say:

> If fields are not enclosed with double quotes, then double quotes may not appear inside the fields.

And this rule is a bit annoying because it leads to unnecessary ambiguity and strictness. I'd say double-quotes _within_ an unquoted field where quoting is allowed can be _literally_ taken as double-quote (without the need for escaping) and that's the approach I took with the [Dsv](https://github.com/atifaziz/Dsv) library:

```c#
var lines = new[] { "field1, \"string1\";\"string2\", field3" };
var row = lines.ParseCsv().Single();

Debug.Assert(row[0] == "field1");
Debug.Assert(row[1] == " \"string1\";\"string2\"");
Debug.Assert(row[2] == " field3");
```

I'm not here to make a shameless plug of Dsv 👼 but hoping to be challenged on the above approach.

**Comment by slorion** [comment]
Well, you just reminded me that the `TrimWhiteSpaces` property can be set to `false` to get the behavior you just described :) For @cantcompile, that may be a better way of handling this case.

```csharp
using (var csv = new DelimitedRecordReader(new StringReader("aaa, \"b\"bb\",ccc")))
{
  csv.TrimWhiteSpaces = false;
  csv.Read();
  Console.WriteLine(csv[1]); // prints ' "b"bb"'
}
```

**Comment by atifaziz** [comment]
> Well, you just reminded me that the `TrimWhiteSpaces` property can be set to `false`

Right, it does solve @cantcompile's problem though I'd say `TrimWhiteSpaces` shouldn't change the parsing logic, just the field value _after_ being parsed.
