### ISSUE TITLE
Write CSV File

### ISSUE THREAD

**Issue by sianmace** [slorion/nlight#24]
I have used your library previously to read csv files, but wanted to write one, but cannot get it to work.  As there are no examples of this or docs, could you cast an eye?

` using MemoryStream memoryStream = new MemoryStream();

            using StreamWriter sw = new StreamWriter(memoryStream, Encoding.UTF8);
            using DelimitedRecordWriter writer = new DelimitedRecordWriter(sw);
            
            writer.Columns.Add(new DelimitedRecordColumn("A", typeof(string)));
            writer.Columns.Add(new DelimitedRecordColumn("B", typeof(string)));
            writer.Columns.Add(new DelimitedRecordColumn("C", typeof(string)));
            writer.Columns.Add(new DelimitedRecordColumn("D", typeof(string)));
            writer.WriteColumnHeaders(false);

            writer.WriteRecord("A", "B", "C", "D");

//            memoryStream.Flush();
   //         memoryStream.Position = 0;

            return File(memoryStream.GetBuffer(), "text/csv", "example.csv");`

I have tried with and without the flush and position setting but i always get a blank file?

**Comment by slorion** [comment]
I suggest you use `StringBuilder` instead. See https://github.com/slorion/nlight/blob/master/src/NLight.Tests.Unit/IO/Text/DelimitedRecordWriterTests/ClassTests.cs for an example.

**Comment by sianmace** [comment]
Ah cool. Will do

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
