### ISSUE TITLE
Unhandled exception when column header name contains a colon (:) character

### ISSUE THREAD

**Issue by bteamsoftware** [slorion/nlight#26]
The code apparently assumes a certain naming convention for column header names where a data type can be specified using the notation "What is your age?:int".  However, the logic throws a TypeLoadException during a call to DelimitedRecordReader.ReadColumnHeaders() if the column header name contains a colon (:) that does not specify a valid type name. i.e. "What is your age : as of 31 Dec?". If the implied type name throws a TypeLoadException, it is probably safest to assume the type should be a string.

**Comment by slorion** [comment]
You can change the type separator character by setting the property `ColumnHeaderTypeSeparator`. Would that solve your issue?

**Comment by bteamsoftware** [comment]
I still think there should be a try-catch block surrounding the call to try to load an assembly based on an assumed type request from the header.  If an exception is thrown, default to string. I think this increases robustness.  I just disabled the feature for now to keep moving forward. I'll circle back at some point. The vendor I get data from has an API available so I'm looking to migrate away from exporting CSV files completely.

**Comment by slorion** [comment]
While I understand your pain point, I disagree about catching an exception and defaulting to string. This could hide a genuine error that should be surfaced.

**Comment by bteamsoftware** [comment]
Or as in my case cause the file to fail to load and render the file useless. I don't control the headers. My feature is to allow users to map fields dynamically so they don't have to adhere to a specific file format, column order, header names, etc.

**Comment by slorion** [comment]
Setting `ColumnHeaderTypeSeparator` to '\0' will in practice disable the feature and should solve your current issue.
