### ISSUE TITLE
FixedWidthRecordReader not Properly Skipping When First Column is not Inclusive of First Character Position

### ISSUE THREAD

**Issue by jasel-lewis** [slorion/nlight#3]
When the first `FixedWidthRecordColumn` does not have a `StartingPosition` of `0`, `FixedWidthRecordReader` starts reading from the first character position in the file instead of jumping to the `StartingPosition` of the first `FixedWidthRecordColumn`.

Example line from fixed-width file:

```
<blank line>
<blank line>
abcdefThisghijklmnop
```

Setup:

```
using (var reader = new FixedWidthRecordReader(new StreamReader(...)))
{
    reader.Columns.Add(new FixedWidthRecordColumn("Field1", typeof(string), 7, 4);

    reader.MissingFieldAction = MissingRecordFieldAction.ReturnNullValue;
    reader.AllRecordsOnSingleLine = true;
    reader.SkipEmptyLines = true;

    ReadResult result = reader.Read(true);
}
```

Expected `reader[0]`:
`This`

Actual `reader[0]`:
`abcd`

Assumption that line 92 and 94 of `FixedWidthRecordReader` are the culprits.  `previousColumn` is null, therefore, `toSkip` is assigned the value `0`.  This is then added to `columnAndIndex.Item1.Width`, when if we're to be skipping, we should be skipping to the `StartingPosition` of `columnAndIndex.Item1`.

**Comment by slorion** [comment]
Thanks for the very detailed bug report and the suggested fix! Very appreciated :)
