### ISSUE TITLE
Attempted Mono port failing with CS0122

### ISSUE THREAD

**Issue by donvnielsen** [slorion/nlight#4]
I'm a long time user and advocate of FasterCSV.  I discovered your NLight product as an alternative for something I was planning on writing.  Thank You!  Now I can just concentrate on the interface.

Anywho. I attempted a port of NLight to the latest and greatest Mono on Mint 17.  I ran into two problems with regards to threading (`<System.Threading.Task>`).  First was a CS0117, which I compensated for by copying the exact Microsoft code required into my own file "AsyncLocal.cs" and building it in.  

The second problem is being more allusive. It is a CS0122 against `<Task.CompletedTask>`.  It is saying that it is not accessible due to protection level.

I'm installing the latest VS to try and chase it down on a windows machine. I was wondering if you had any thoughts on this, and maybe some advice on a work around.  Much appreciated. I am way out of my comfort zone with threading.  I know zero, maybe less, about threading.

Have a good one!

``` C#
        private static Task EndSession(DataSession<DbDataSessionState> session)
        {
            if (session == null) throw new ArgumentNullException(nameof(session));

            if (session.State.ConnectionHandledByReader)
                return Task.CompletedTask;
            else
                return Task.Run(
                    () =>
                    {
                        session.State.Connection.Close();
                        session.State.Connection.Dispose();
                    });
        }
```

**Comment by slorion** [comment]
`AsyncLocal` and `Task.CompletedTask` are additions to .NET 4.6. You can use `Task.FromResult(0)` as a replacement of `Task.CompletedTask`.
