### ISSUE TITLE
Request to open up ValueConverter

### ISSUE THREAD

**Issue by phrrngtn** [slorion/nlight#5]
Hi,
I find your assembly very useful. I have a couple of usability suggestions based on my experiences.

Is this the correct way to change the datatype of a column after reading in the header? (I have several datasets where I have separate metadata of column-name to column-types)

```
           reader.Columns["ts"]=new DelimitedRecordColumn("ts", typeof(System.DateTime));
```

Some of my data-sets have Excel-style currencies which require calls such as this to transform the values. It would be very convenient if the application could pass in a lambda/callable to do the conversion.

```
    object[] row = new object[reader.Columns.Count];
    reader.CopyCurrentRecordTo(row);

    row[5] = float.Parse(row[5].ToString(), System.Globalization.NumberStyles.Currency);
    row[6] = int.Parse(row[6].ToString(), System.Globalization.NumberStyles.Currency);
    row[7] = float.Parse(row[7].ToString(), System.Globalization.NumberStyles.Currency);
```

thanks again for your work.
pjjH

**Comment by slorion** [comment]
Hello, sorry for the late answer, I have many things going on. You can support currency format like this:

`reader.ValueConverter.FloatingPointNumberStyles = NumberStyles.Currency`

This is a setting for all columns thought, is that OK for you ? If you need more fine grained control, I could add a per column override. Let me know!

**Comment by phrrngtn** [comment]
Yes, for generality I would like it on a per-column basis. My use case is 
nearly always going to be writing to a database so ideally I could use the 
type information from the destination table metadata to do some coercion 
in the CSV reader. This may or may not be quite straightforward: my 
knowledge of the .NET framework is quite shallow.

pjjH

**Comment by slorion** [comment]
Ok, I will have a look at that when I have some free time.

**Comment by JMoelands** [comment]
I Agree on this, would be very nice

**Comment by slorion** [comment]
Do you have a specific example? I am asking because thinking about it again, why would someone use a number style for some columns and another for some other columns?

**Comment by JMoelands** [comment]
We would like to be able to assign a string converter delegate for every column. And then we also can fix the formatting issue as stated above? And make the " use your string converter / data type detector" as an option.

Hope this is clear.

**Comment by slorion** [comment]
Thanks for the feedback. It's done :)

**Comment by JMoelands** [comment]
Thanks for the quick response (again), very nice. Is there a specific reason why you did not choose to implemented it as a delegate which we can assign to each column. That way you provide a lot of freedom to implement the conversion strategy (can be use case specific).

**Comment by slorion** [comment]
Hum, no specific reason besides that StringValueConverter already supports all the simple value types. Only use case that I see for a delegate is if a field contains a complex data type. I never saw that in a CSV and one could argue that JSON or some other format is more appropriate in that case. Sorry to ask again, but do you have some example where a delegate would be required ?

**Comment by JMoelands** [comment]
Hi Slorion,

Examples:
-	pre-processing data before standard parsing can take place, for instance 
1. when no decimal separator is used in fixed width file formats
2. When minor “noise” needs to be filtered out of a mostly correct formatted file (can be caused by manual creation / editing of csv files)
3. injecting the timezone information into the text value before parsing to DateTime, although this could count as converting instead of parsing
4. When u want to add custom converters (for example, dutch system uses J and N for a bit field)

We need to think about Unicode, because this has already took place before it became a .NET string.

Delegate would really be nice, can't you support both (as u have now, or with a delegate?) it makes the framework much more use-able, customizable

**Comment by JMoelands** [comment]
We are using your framework for DWH loading so we see a lot of cases in daily practice. We always strive to use correct data type and interface specifications (and then it is a piece of case) and what you enhanced now, works, but there are always parties with old (mainframe) and other systems that are not able to do so. And sometimes the parties have developers who think they know the best and we can not push them to change ;-)

**Comment by slorion** [comment]
Humm, you raise valid points. One way to handle these scenarios is to handle them inside the RecordParsed event. What do you think about this solution?
