### ISSUE TITLE
Do RecordWrtiers Write Headers

### ISSUE THREAD

**Issue by alanschrank** [slorion/nlight#6]
I'm experimenting with the DelimitedRecordWriter for the first time.
I don't see a method that would write a header based on the defined columns. Is there one and I am missing it, is there another simple way?
If it doesn't exist, do you think it should?
For the header I would expect it to iterate through the columns writing the name of each as a string even if the type of the column is something else

**Comment by slorion** [comment]
I'm sorry for the late reply. You are right, there is no method doing what you ask and I agree it would be a useful addition. It is only a matter of calling `WriteRecord(this.Columns.Keys)`, but having a shortcut is convenient.
