### ISSUE TITLE
DelimitedRecordWriter columns

### ISSUE THREAD

**Issue by nickrossiter** [slorion/nlight#8]
Hi Sébastien,

I have been using the NLight DelimitedRecordReader with great success. I now would like to use the DeimitedRecordWriter to produce csv files but I am a bit confused as to how I define the columns of the file to be produced. The Columns property is read only and I cannot see any method to set it. Am I being a bit dense?

Thanks

Nick

**Comment by slorion** [comment]
That property is a `IDictionary<string, DelimitedRecordColumn>`, so simply do `writer.Columns.Add("myColumn", new DelimitedRecordColumn(...))`

**Comment by nickrossiter** [comment]
That's what I thought, except that the Columns property doesn't have a setter.

from TextRecordWriter.cs :-

public abstract partial class TextRecordWriter<TColumn>
        : TextRecordWriter, IDisposable
        where TColumn : RecordColumn
    {
.
.
.
public RecordColumnCollection<TColumn> Columns { get; }
.
.
.

**Comment by slorion** [comment]
Please read my comment again .. you do not set the property, you call Add on it as I explained.

**Comment by nickrossiter** [comment]
Sorry, my mistake. Not sure what I was doing but it was obviously wrong!
Thank you for your support.

Nick
